### ISSUE TITLE
test scenarios

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/gogridengine#12]
Per #11 

we should have xml files in testdata with the following outputs for reference:

scenarios: 
* 0 workers
* 1 worker
* 2 (many) workers

queued/running states:

* 0 jobs queued/0 jobs running  
* 0 jobs queued/1 job running 
* 0 jobs queued/2 jobs running 
* 2 jobs queued + 1 job running
* 2 jobs queued + 10 jobs running (imbalanced job distribution so multiple but non-equal number jobs running on nodes, in this case likely 8/2)
* 1000 jobs queued + full worker saturation
* 100000 jobs queued + full worker saturation

**Comment by shairozan** [comment]
Do they actually need to come from the grid, or would it be fine for me to generate the structs and serialize them down?
